"""Scaffold: Application code (FastAPI backend + React frontend stubs)."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from ignition.config import IgnitionConfig
from ignition.models import PRD

TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent.parent / "templates"


def scaffold_app(prd: PRD, config: IgnitionConfig) -> list[str]:
    """Generate application boilerplate."""
    work = config.ensure_work_dir()
    files: list[str] = []

    files.extend(_scaffold_backend(prd, config, work))
    files.extend(_scaffold_frontend(prd, config, work))

    return files


def _scaffold_backend(prd: PRD, config: IgnitionConfig, work: Path) -> list[str]:
    """Generate FastAPI backend."""
    backend = work / "app" / "backend"
    backend.mkdir(parents=True, exist_ok=True)

    files: list[str] = []

    # Try Jinja2 templates, fallback to inline
    try:
        env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
        ctx = {"project_name": prd.project_name, "domain": prd.domain}

        for tpl_name, dest_name in [
            ("app/backend/main.py.j2", "main.py"),
            ("app/backend/requirements.txt.j2", "requirements.txt"),
            ("app/backend/Dockerfile.j2", "Dockerfile"),
        ]:
            tpl = env.get_template(tpl_name)
            dest = backend / dest_name
            dest.write_text(tpl.render(**ctx), encoding="utf-8")
            files.append(str(dest.relative_to(work)))
    except Exception:
        files.extend(_inline_backend(prd, backend, work))

    return files


def _inline_backend(prd: PRD, backend: Path, work: Path) -> list[str]:
    """Fallback: generate inline backend files."""
    files: list[str] = []

    # main.py
    main = backend / "main.py"
    main.write_text(
        f'''\
"""FastAPI application for {prd.project_name}."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{prd.project_name}",
    description="Generated by IgnitionStack — domain: {prd.domain}",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health():
    return {{"status": "ok", "project": "{prd.project_name}"}}


@app.get("/api/v1/info")
async def info():
    return {{
        "project": "{prd.project_name}",
        "domain": "{prd.domain}",
        "version": "0.1.0",
    }}
''',
        encoding="utf-8",
    )
    files.append(str(main.relative_to(work)))

    # requirements.txt
    req = backend / "requirements.txt"
    req.write_text(
        "fastapi>=0.110\nuvicorn[standard]>=0.29\npydantic>=2.5\n",
        encoding="utf-8",
    )
    files.append(str(req.relative_to(work)))

    # Dockerfile
    df = backend / "Dockerfile"
    df.write_text(
        """\
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
""",
        encoding="utf-8",
    )
    files.append(str(df.relative_to(work)))

    return files


def _scaffold_frontend(prd: PRD, config: IgnitionConfig, work: Path) -> list[str]:
    """Generate React + Vite frontend stub."""
    frontend = work / "app" / "frontend"
    frontend.mkdir(parents=True, exist_ok=True)

    files: list[str] = []

    # package.json
    pkg = frontend / "package.json"
    pkg.write_text(
        f"""\
{{
  "name": "{prd.project_name}-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }},
  "devDependencies": {{
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.0",
    "typescript": "~5.6.0",
    "vite": "^6.0.0"
  }}
}}
""",
        encoding="utf-8",
    )
    files.append(str(pkg.relative_to(work)))

    # index.html
    idx = frontend / "index.html"
    idx.write_text(
        f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{prd.project_name}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>
""",
        encoding="utf-8",
    )
    files.append(str(idx.relative_to(work)))

    return files
