"""Scaffold: Database schema and migrations."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from ignition.config import IgnitionConfig
from ignition.models import PRD

TEMPLATES_DIR = Path(__file__).resolve().parent.parent.parent.parent / "templates"


def scaffold_database(prd: PRD, config: IgnitionConfig) -> list[str]:
    """Generate database migration and seed files."""
    work = config.ensure_work_dir()
    db_dir = work / "db" / "migrations"
    db_dir.mkdir(parents=True, exist_ok=True)

    files: list[str] = []

    # Try Jinja2 template first, fallback to inline
    try:
        env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
        tpl = env.get_template("db/001_initial.sql.j2")
        content = tpl.render(project_name=prd.project_name, domain=prd.domain)
    except Exception:
        content = _default_migration(prd)

    dest = db_dir / "001_initial.sql"
    dest.write_text(content, encoding="utf-8")
    files.append(str(dest.relative_to(work)))

    # Seed data
    seed = work / "db" / "seed.sql"
    seed.write_text(_seed_data(prd), encoding="utf-8")
    files.append(str(seed.relative_to(work)))

    return files


def _default_migration(prd: PRD) -> str:
    schema = prd.project_name.replace("-", "_")
    return f"""\
-- Initial schema for {prd.project_name}
-- Domain: {prd.domain}
-- Generated by IgnitionStack

CREATE SCHEMA IF NOT EXISTS {schema};

CREATE TABLE {schema}.users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email       VARCHAR(255) NOT NULL UNIQUE,
    full_name   VARCHAR(255) NOT NULL,
    role        VARCHAR(50) NOT NULL DEFAULT 'user',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE {schema}.audit_log (
    id          BIGSERIAL PRIMARY KEY,
    user_id     UUID REFERENCES {schema}.users(id),
    action      VARCHAR(100) NOT NULL,
    resource    VARCHAR(255),
    details     JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_log_user   ON {schema}.audit_log(user_id);
CREATE INDEX idx_audit_log_action ON {schema}.audit_log(action);
CREATE INDEX idx_audit_log_time   ON {schema}.audit_log(created_at);
"""


def _seed_data(prd: PRD) -> str:
    schema = prd.project_name.replace("-", "_")
    return f"""\
-- Seed data for {prd.project_name}
-- Generated by IgnitionStack

INSERT INTO {schema}.users (email, full_name, role) VALUES
    ('admin@example.com', 'Admin User', 'admin'),
    ('demo@example.com', 'Demo User', 'user');
"""
